import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.resolve(__dirname, '../../../.env') });
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

import connectDB from '../config/db.js';
import Technician from '../models/Technician.js';
import ServiceRequest from '../models/ServiceRequest.js';
import Assignment from '../models/Assignment.js';
import ScheduleVersion from '../models/ScheduleVersion.js';
import AuditLog from '../models/AuditLog.js';
import Notification from '../models/Notification.js';

export const SEED_TECHNICIANS = [
  {
    technicianId: 'TECH-001',
    name: 'Alex Johnson',
    role: 'AC Specialist',
    region: 'Jaipur North',
    skills: ['AC Repair', 'HVAC', 'Preventive Maintenance'],
    status: 'Available',
    availability: '09:00 - 17:00',
    workingHours: { start: '09:00', end: '17:00' },
    dailyWorkload: 4.0,
    currentWorkloadHours: 4.0,
    maxWorkloadHours: 8,
    rating: 4.9,
    jobsToday: 2,
    completedJobsToday: 0,
    avatar: 'AJ',
  },
  {
    technicianId: 'TECH-002',
    name: 'Rahul Sharma',
    role: 'Senior Electrician',
    region: 'Jaipur Central',
    skills: ['Electrical Repair', 'Wiring', 'Smart Metering'],
    status: 'Available',
    availability: '09:00 - 17:00',
    workingHours: { start: '09:00', end: '17:00' },
    dailyWorkload: 4.0,
    currentWorkloadHours: 4.0,
    maxWorkloadHours: 8,
    rating: 4.8,
    jobsToday: 2,
    completedJobsToday: 0,
    avatar: 'RS',
  },
  {
    technicianId: 'TECH-003',
    name: 'Priya Verma',
    role: 'Plumbing Lead',
    region: 'Jaipur South',
    skills: ['Plumbing', 'Pipe Fitting', 'Water Heater Repair'],
    status: 'Available',
    availability: '09:00 - 17:00',
    workingHours: { start: '09:00', end: '17:00' },
    dailyWorkload: 3.5,
    currentWorkloadHours: 3.5,
    maxWorkloadHours: 8,
    rating: 4.9,
    jobsToday: 2,
    completedJobsToday: 0,
    avatar: 'PV',
  },
  {
    technicianId: 'TECH-004',
    name: 'Aman Singh',
    role: 'HVAC Technician',
    region: 'Jaipur West',
    skills: ['HVAC', 'Refrigeration', 'Duct Cleaning'],
    status: 'Available',
    availability: '09:00 - 17:00',
    workingHours: { start: '09:00', end: '17:00' },
    dailyWorkload: 3.5,
    currentWorkloadHours: 3.5,
    maxWorkloadHours: 8,
    rating: 4.7,
    jobsToday: 2,
    completedJobsToday: 1,
    avatar: 'AS',
  },
  {
    technicianId: 'TECH-005',
    name: 'Neha Kapoor',
    role: 'Appliance Expert',
    region: 'Jaipur East',
    skills: ['Appliance Repair', 'Washing Machine', 'Microwave'],
    status: 'Unavailable',
    availability: 'On Leave',
    workingHours: { start: '09:00', end: '17:00' },
    dailyWorkload: 0,
    currentWorkloadHours: 0,
    maxWorkloadHours: 8,
    rating: 4.6,
    jobsToday: 0,
    completedJobsToday: 0,
    avatar: 'NK',
  },
];

export const SEED_REQUESTS = [
  {
    requestId: 'REQ-001',
    customer: 'Rohan Mehta',
    phone: '+91 98765 43210',
    location: 'Jaipur North, Malviya Nagar',
    region: 'Jaipur North',
    requiredSkill: 'AC Repair',
    priority: 'High',
    duration: '2 hours',
    durationHours: 2,
    preferredWindow: '09:00 - 12:00',
    startTime: '09:00',
    endTime: '11:00',
    status: 'ASSIGNED',
    assignedTechId: 'TECH-001',
    assignedTechnician: 'Alex Johnson',
    assignedTechName: 'Alex Johnson',
    notes: 'Compressor making loud humming sound and cooling is suboptimal.',
    address: '42, Pearl Court, Malviya Nagar, Jaipur North',
  },
  {
    requestId: 'REQ-002',
    customer: 'Sunita Rao',
    phone: '+91 98765 43211',
    location: 'Jaipur Central, C-Scheme',
    region: 'Jaipur Central',
    requiredSkill: 'Electrical Repair',
    priority: 'Medium',
    duration: '2 hours',
    durationHours: 2,
    preferredWindow: '10:00 - 13:00',
    startTime: '10:00',
    endTime: '12:00',
    status: 'ASSIGNED',
    assignedTechId: 'TECH-002',
    assignedTechnician: 'Rahul Sharma',
    assignedTechName: 'Rahul Sharma',
    notes: 'Main distribution board circuit breaker tripping periodically.',
    address: '12-A, Ashok Marg, C-Scheme, Jaipur Central',
  },
  {
    requestId: 'REQ-003',
    customer: 'Vikram Choudhury',
    phone: '+91 98765 43212',
    location: 'Jaipur South, Mansarovar',
    region: 'Jaipur South',
    requiredSkill: 'Plumbing',
    priority: 'High',
    duration: '2 hours',
    durationHours: 2,
    preferredWindow: '12:00 - 15:00',
    startTime: '12:00',
    endTime: '14:00',
    status: 'ASSIGNED',
    assignedTechId: 'TECH-003',
    assignedTechnician: 'Priya Verma',
    assignedTechName: 'Priya Verma',
    notes: 'High pressure line burst under kitchen sink, emergency shutoff active.',
    address: 'Plot 78, Ward 22, Mansarovar, Jaipur South',
  },
  {
    requestId: 'REQ-004',
    customer: 'Ananya Deshmukh',
    phone: '+91 98765 43213',
    location: 'Jaipur North, Malviya Nagar',
    region: 'Jaipur North',
    requiredSkill: 'AC Repair',
    priority: 'Normal',
    duration: '2 hours',
    durationHours: 2,
    preferredWindow: '13:00 - 16:00',
    startTime: '13:00',
    endTime: '15:00',
    status: 'ASSIGNED',
    assignedTechId: 'TECH-001',
    assignedTechnician: 'Alex Johnson',
    assignedTechName: 'Alex Johnson',
    notes: 'Seasonal filter cleaning and gas pressure check before summer.',
    address: 'Flat 301, Silver Crest, Malviya Nagar, Jaipur North',
  },
  {
    requestId: 'REQ-005',
    customer: 'Kavita Joshi',
    phone: '+91 98765 43214',
    location: 'Jaipur South, Vaishali Nagar',
    region: 'Jaipur South',
    requiredSkill: 'Plumbing',
    priority: 'Normal',
    duration: '1.5 hours',
    durationHours: 1.5,
    preferredWindow: '09:00 - 12:00',
    startTime: '09:30',
    endTime: '11:00',
    status: 'ASSIGNED',
    assignedTechId: 'TECH-003',
    assignedTechnician: 'Priya Verma',
    assignedTechName: 'Priya Verma',
    notes: 'Bathroom mixer replacement and fixture tight sealing.',
    address: '88, Block C, Vaishali Nagar, Jaipur South',
  },
  {
    requestId: 'REQ-006',
    customer: 'Deepak Saxena',
    phone: '+91 98765 43215',
    location: 'Jaipur Central, C-Scheme',
    region: 'Jaipur Central',
    requiredSkill: 'Electrical Repair',
    priority: 'Normal',
    duration: '2 hours',
    durationHours: 2,
    preferredWindow: '14:00 - 17:00',
    startTime: '14:00',
    endTime: '16:00',
    status: 'ASSIGNED',
    assignedTechId: 'TECH-002',
    assignedTechnician: 'Rahul Sharma',
    assignedTechName: 'Rahul Sharma',
    notes: 'Installation of 3 smart touch-switches and earthing verification.',
    address: 'B-14, Subhash Marg, C-Scheme, Jaipur Central',
  },
  {
    requestId: 'REQ-007',
    customer: 'Manish Parekh',
    phone: '+91 98765 43216',
    location: 'Jaipur East, Jagatpura',
    region: 'Jaipur East',
    requiredSkill: 'AC Maintenance',
    priority: 'High',
    duration: '2 hours',
    durationHours: 2,
    preferredWindow: '11:00 - 14:00',
    startTime: null,
    endTime: null,
    status: 'UNASSIGNED',
    assignedTechId: null,
    assignedTechnician: null,
    assignedTechName: null,
    issueFlag: 'No valid technician available in East region',
    notes: 'Commercial AC indoor unit not responding to remote control.',
    address: 'Tower 4, Skylight Residency, Jagatpura, Jaipur East',
  },
  {
    requestId: 'REQ-008',
    customer: 'Tarun Mathur',
    phone: '+91 98765 43217',
    location: 'Jaipur West, Ajmer Road',
    region: 'Jaipur West',
    requiredSkill: 'HVAC',
    priority: 'High',
    duration: '2 hours',
    durationHours: 2,
    preferredWindow: '13:00 - 16:00',
    startTime: '13:00',
    endTime: '15:00',
    status: 'ASSIGNED',
    assignedTechId: 'TECH-004',
    assignedTechnician: 'Aman Singh',
    assignedTechName: 'Aman Singh',
    notes: 'Ducted air unit vibrating noisily during compressor kickoff.',
    address: 'Villa 19, Green Meadows, Ajmer Road, Jaipur West',
  },
  {
    requestId: 'REQ-009',
    customer: 'Gaurav Singhal',
    phone: '+91 98765 43218',
    location: 'Jaipur Central, MI Road',
    region: 'Jaipur Central',
    requiredSkill: 'Electrical Repair',
    priority: 'Critical',
    duration: '2 hours',
    durationHours: 2,
    preferredWindow: '15:00 - 17:00',
    startTime: null,
    endTime: null,
    status: 'UNASSIGNED',
    assignedTechId: null,
    assignedTechnician: null,
    assignedTechName: null,
    issueFlag: 'Narrow time window · High risk of overrun',
    notes: 'Power backup phase failure affecting medical refrigeration equipment.',
    address: 'Shop 5, Heritage Arcade, MI Road, Jaipur Central',
  },
  {
    requestId: 'REQ-010',
    customer: 'Meenakshi Sundaram',
    phone: '+91 98765 43219',
    location: 'Jaipur West, Nirman Nagar',
    region: 'Jaipur West',
    requiredSkill: 'HVAC',
    priority: 'Normal',
    duration: '1.5 hours',
    durationHours: 1.5,
    preferredWindow: '09:00 - 11:00',
    startTime: '09:00',
    endTime: '10:30',
    status: 'COMPLETED',
    isProtectedCompleted: true,
    assignedTechId: 'TECH-004',
    assignedTechnician: 'Aman Singh',
    assignedTechName: 'Aman Singh',
    notes: 'Annual servicing completed, new copper coil filter placed.',
    address: 'A-21, Lane 3, Nirman Nagar, Jaipur West',
  },
];

export const SEED_ASSIGNMENTS = [
  {
    assignmentId: 'ASG-REQ-001',
    requestId: 'REQ-001',
    technicianId: 'TECH-001',
    technicianName: 'Alex Johnson',
    customer: 'Rohan Mehta',
    skill: 'AC Repair',
    region: 'Jaipur North',
    startTime: '09:00',
    endTime: '11:00',
    timeSlot: '09:00 – 11:00',
    status: 'Scheduled',
    protected: false,
  },
  {
    assignmentId: 'ASG-REQ-002',
    requestId: 'REQ-002',
    technicianId: 'TECH-002',
    technicianName: 'Rahul Sharma',
    customer: 'Sunita Rao',
    skill: 'Electrical Repair',
    region: 'Jaipur Central',
    startTime: '10:00',
    endTime: '12:00',
    timeSlot: '10:00 – 12:00',
    status: 'Scheduled',
    protected: false,
  },
  {
    assignmentId: 'ASG-REQ-003',
    requestId: 'REQ-003',
    technicianId: 'TECH-003',
    technicianName: 'Priya Verma',
    customer: 'Vikram Choudhury',
    skill: 'Plumbing',
    region: 'Jaipur South',
    startTime: '12:00',
    endTime: '14:00',
    timeSlot: '12:00 – 14:00',
    status: 'Scheduled',
    protected: false,
  },
  {
    assignmentId: 'ASG-REQ-004',
    requestId: 'REQ-004',
    technicianId: 'TECH-001',
    technicianName: 'Alex Johnson',
    customer: 'Ananya Deshmukh',
    skill: 'AC Repair',
    region: 'Jaipur North',
    startTime: '13:00',
    endTime: '15:00',
    timeSlot: '13:00 – 15:00',
    status: 'Scheduled',
    protected: false,
  },
  {
    assignmentId: 'ASG-REQ-005',
    requestId: 'REQ-005',
    technicianId: 'TECH-003',
    technicianName: 'Priya Verma',
    customer: 'Kavita Joshi',
    skill: 'Plumbing',
    region: 'Jaipur South',
    startTime: '09:30',
    endTime: '11:00',
    timeSlot: '09:30 – 11:00',
    status: 'Scheduled',
    protected: false,
  },
  {
    assignmentId: 'ASG-REQ-006',
    requestId: 'REQ-006',
    technicianId: 'TECH-002',
    technicianName: 'Rahul Sharma',
    customer: 'Deepak Saxena',
    skill: 'Electrical Repair',
    region: 'Jaipur Central',
    startTime: '14:00',
    endTime: '16:00',
    timeSlot: '14:00 – 16:00',
    status: 'Scheduled',
    protected: false,
  },
  {
    assignmentId: 'ASG-REQ-008',
    requestId: 'REQ-008',
    technicianId: 'TECH-004',
    technicianName: 'Aman Singh',
    customer: 'Tarun Mathur',
    skill: 'HVAC',
    region: 'Jaipur West',
    startTime: '13:00',
    endTime: '15:00',
    timeSlot: '13:00 – 15:00',
    status: 'Scheduled',
    protected: false,
  },
  {
    assignmentId: 'ASG-REQ-010',
    requestId: 'REQ-010',
    technicianId: 'TECH-004',
    technicianName: 'Aman Singh',
    customer: 'Meenakshi Sundaram',
    skill: 'HVAC',
    region: 'Jaipur West',
    startTime: '09:00',
    endTime: '10:30',
    timeSlot: '09:00 – 10:30',
    status: 'Completed',
    protected: true,
    isProtectedCompleted: true,
    reason: 'Completed — Protected from replanning.',
  },
];

export const SEED_VERSIONS = [
  {
    versionId: 'VER-001',
    version: 'v1',
    versionNumber: 1,
    status: 'Confirmed',
    createdBy: 'AI Dispatch Engine',
    createdAtString: 'Yesterday, 19:00 PM',
    trigger: 'Initial overnight batch optimization plan',
    reason: 'Initial overnight batch optimization plan',
    isCurrent: false,
    totalAssignments: 8,
    unassignedCount: 2,
    assignmentsSnapshot: [
      { id: 'REQ-001', requestId: 'REQ-001', customer: 'Rohan Mehta', skill: 'AC Repair', technician: 'Alex Johnson', startTime: '09:00', endTime: '11:00', timeSlot: '09:00 – 11:00', status: 'Scheduled', region: 'Jaipur North' },
      { id: 'REQ-002', requestId: 'REQ-002', customer: 'Sunita Rao', skill: 'Electrical Repair', technician: 'Rahul Sharma', startTime: '10:00', endTime: '12:00', timeSlot: '10:00 – 12:00', status: 'Scheduled', region: 'Jaipur Central' },
      { id: 'REQ-003', requestId: 'REQ-003', customer: 'Vikram Choudhury', skill: 'Plumbing', technician: 'Priya Verma', startTime: '12:00', endTime: '14:00', timeSlot: '12:00 – 14:00', status: 'Scheduled', region: 'Jaipur South' },
      { id: 'REQ-004', requestId: 'REQ-004', customer: 'Ananya Deshmukh', skill: 'AC Repair', technician: 'Rahul Sharma', startTime: '10:00', endTime: '12:00', timeSlot: '10:00 – 12:00', status: 'Scheduled', region: 'Jaipur North' },
      { id: 'REQ-005', requestId: 'REQ-005', customer: 'Kavita Joshi', skill: 'Plumbing', technician: 'Priya Verma', startTime: '09:30', endTime: '11:00', timeSlot: '09:30 – 11:00', status: 'Scheduled', region: 'Jaipur South' },
      { id: 'REQ-006', requestId: 'REQ-006', customer: 'Deepak Saxena', skill: 'Electrical Repair', technician: 'Rahul Sharma', startTime: '14:00', endTime: '16:00', timeSlot: '14:00 – 16:00', status: 'Scheduled', region: 'Jaipur Central' },
      { id: 'REQ-007', requestId: 'REQ-007', customer: 'Manish Parekh', skill: 'AC Maintenance', technician: null, startTime: null, endTime: null, timeSlot: 'None', status: 'Unassigned', region: 'Jaipur East' },
      { id: 'REQ-008', requestId: 'REQ-008', customer: 'Tarun Mathur', skill: 'HVAC', technician: 'Aman Singh', startTime: '13:00', endTime: '15:00', timeSlot: '13:00 – 15:00', status: 'Scheduled', region: 'Jaipur West' },
      { id: 'REQ-009', requestId: 'REQ-009', customer: 'Gaurav Singhal', skill: 'Electrical Repair', technician: null, startTime: null, endTime: null, timeSlot: 'None', status: 'Unassigned', priority: 'Critical', region: 'Jaipur Central' },
      { id: 'REQ-010', requestId: 'REQ-010', customer: 'Meenakshi Sundaram', skill: 'HVAC', technician: 'Aman Singh', startTime: '09:00', endTime: '10:30', timeSlot: '09:00 – 10:30', status: 'Completed', isProtectedCompleted: true, region: 'Jaipur West' },
    ],
  },
  {
    versionId: 'VER-002',
    version: 'v2',
    versionNumber: 2,
    status: 'Confirmed',
    createdBy: 'Alex Rivera',
    createdAtString: 'Today, 08:30 AM',
    trigger: 'Morning dispatcher manual adjustment for high priority requests',
    reason: 'Morning dispatcher manual adjustment for high priority requests',
    isCurrent: false,
    totalAssignments: 8,
    unassignedCount: 2,
    assignmentsSnapshot: [
      { id: 'REQ-001', requestId: 'REQ-001', customer: 'Rohan Mehta', skill: 'AC Repair', technician: 'Alex Johnson', startTime: '09:00', endTime: '11:00', timeSlot: '09:00 – 11:00', status: 'Scheduled', region: 'Jaipur North' },
      { id: 'REQ-002', requestId: 'REQ-002', customer: 'Sunita Rao', skill: 'Electrical Repair', technician: 'Rahul Sharma', startTime: '10:00', endTime: '12:00', timeSlot: '10:00 – 12:00', status: 'Scheduled', region: 'Jaipur Central' },
      { id: 'REQ-003', requestId: 'REQ-003', customer: 'Vikram Choudhury', skill: 'Plumbing', technician: 'Priya Verma', startTime: '12:00', endTime: '14:00', timeSlot: '12:00 – 14:00', status: 'Scheduled', region: 'Jaipur South' },
      { id: 'REQ-004', requestId: 'REQ-004', customer: 'Ananya Deshmukh', skill: 'AC Repair', technician: 'Rahul Sharma', startTime: '10:00', endTime: '12:00', timeSlot: '10:00 – 12:00', status: 'Scheduled', region: 'Jaipur North' },
      { id: 'REQ-005', requestId: 'REQ-005', customer: 'Kavita Joshi', skill: 'Plumbing', technician: 'Priya Verma', startTime: '09:30', endTime: '11:00', timeSlot: '09:30 – 11:00', status: 'Scheduled', region: 'Jaipur South' },
      { id: 'REQ-006', requestId: 'REQ-006', customer: 'Deepak Saxena', skill: 'Electrical Repair', technician: 'Rahul Sharma', startTime: '14:00', endTime: '16:00', timeSlot: '14:00 – 16:00', status: 'Scheduled', region: 'Jaipur Central' },
      { id: 'REQ-007', requestId: 'REQ-007', customer: 'Manish Parekh', skill: 'AC Maintenance', technician: null, startTime: null, endTime: null, timeSlot: 'None', status: 'Unassigned', region: 'Jaipur East' },
      { id: 'REQ-008', requestId: 'REQ-008', customer: 'Tarun Mathur', skill: 'HVAC', technician: 'Aman Singh', startTime: '13:00', endTime: '15:00', timeSlot: '13:00 – 15:00', status: 'Scheduled', region: 'Jaipur West' },
      { id: 'REQ-009', requestId: 'REQ-009', customer: 'Gaurav Singhal', skill: 'Electrical Repair', technician: null, startTime: null, endTime: null, timeSlot: 'None', status: 'Unassigned', priority: 'Critical', region: 'Jaipur Central' },
      { id: 'REQ-010', requestId: 'REQ-010', customer: 'Meenakshi Sundaram', skill: 'HVAC', technician: 'Aman Singh', startTime: '09:00', endTime: '10:30', timeSlot: '09:00 – 10:30', status: 'Completed', isProtectedCompleted: true, region: 'Jaipur West' },
    ],
  },
  {
    versionId: 'VER-003',
    version: 'v3',
    versionNumber: 3,
    status: 'Draft',
    createdBy: 'AI Dispatch Engine',
    createdAtString: 'Today, 09:42 AM',
    trigger: 'Replanned due to Rahul Sharma sudden unavailability',
    reason: 'Replanned due to Rahul Sharma sudden unavailability',
    isCurrent: true,
    totalAssignments: 8,
    unassignedCount: 2,
    assignmentsSnapshot: [
      { id: 'REQ-001', requestId: 'REQ-001', customer: 'Rohan Mehta', skill: 'AC Repair', technician: 'Alex Johnson', startTime: '09:00', endTime: '11:00', timeSlot: '09:00 – 11:00', status: 'Scheduled', region: 'Jaipur North' },
      { id: 'REQ-002', requestId: 'REQ-002', customer: 'Sunita Rao', skill: 'Electrical Repair', technician: 'Rahul Sharma', startTime: '10:00', endTime: '12:00', timeSlot: '10:00 – 12:00', status: 'Scheduled', region: 'Jaipur Central' },
      { id: 'REQ-003', requestId: 'REQ-003', customer: 'Vikram Choudhury', skill: 'Plumbing', technician: 'Priya Verma', startTime: '12:00', endTime: '14:00', timeSlot: '12:00 – 14:00', status: 'Scheduled', region: 'Jaipur South' },
      { id: 'REQ-004', requestId: 'REQ-004', customer: 'Ananya Deshmukh', skill: 'AC Repair', technician: 'Alex Johnson', startTime: '13:00', endTime: '15:00', timeSlot: '13:00 – 15:00', status: 'Scheduled', region: 'Jaipur North' },
      { id: 'REQ-005', requestId: 'REQ-005', customer: 'Kavita Joshi', skill: 'Plumbing', technician: 'Priya Verma', startTime: '09:30', endTime: '11:00', timeSlot: '09:30 – 11:00', status: 'Scheduled', region: 'Jaipur South' },
      { id: 'REQ-006', requestId: 'REQ-006', customer: 'Deepak Saxena', skill: 'Electrical Repair', technician: 'Rahul Sharma', startTime: '14:00', endTime: '16:00', timeSlot: '14:00 – 16:00', status: 'Scheduled', region: 'Jaipur Central' },
      { id: 'REQ-007', requestId: 'REQ-007', customer: 'Manish Parekh', skill: 'AC Maintenance', technician: null, startTime: null, endTime: null, timeSlot: 'None', status: 'Unassigned', region: 'Jaipur East' },
      { id: 'REQ-008', requestId: 'REQ-008', customer: 'Tarun Mathur', skill: 'HVAC', technician: 'Aman Singh', startTime: '13:00', endTime: '15:00', timeSlot: '13:00 – 15:00', status: 'Scheduled', region: 'Jaipur West' },
      { id: 'REQ-009', requestId: 'REQ-009', customer: 'Gaurav Singhal', skill: 'Electrical Repair', technician: null, startTime: null, endTime: null, timeSlot: 'None', status: 'Unassigned', priority: 'Critical', region: 'Jaipur Central' },
      { id: 'REQ-010', requestId: 'REQ-010', customer: 'Meenakshi Sundaram', skill: 'HVAC', technician: 'Aman Singh', startTime: '09:00', endTime: '10:30', timeSlot: '09:00 – 10:30', status: 'Completed', isProtectedCompleted: true, region: 'Jaipur West', reason: 'Completed — Protected from replanning.' },
    ],
  },
];

export const SEED_NOTIFICATIONS = [
  {
    notificationId: 'NOTIF-001',
    title: 'Schedule v3 Draft Generated',
    message: 'AI Dispatch Engine generated schedule v3 optimization with 1 reassignment.',
    description: 'AI Dispatch Engine generated schedule v3 optimization with 1 reassignment.',
    timestamp: '15 mins ago',
    type: 'Schedule Updates',
    category: 'schedule',
    read: false,
    unread: true,
    severity: 'info',
  },
  {
    notificationId: 'NOTIF-002',
    title: 'Emergency Request Created',
    message: 'Critical electrical fault REQ-009 logged for Jaipur Central (MI Road).',
    description: 'Critical electrical fault REQ-009 logged for Jaipur Central (MI Road).',
    timestamp: '45 mins ago',
    type: 'Emergency',
    category: 'emergency',
    read: false,
    unread: true,
    severity: 'danger',
  },
  {
    notificationId: 'NOTIF-003',
    title: 'Assignment Confirmed',
    message: 'REQ-001 started by Alex Johnson at Royal Palms, Sector 4.',
    description: 'REQ-001 started by Alex Johnson at Royal Palms, Sector 4.',
    timestamp: '1 hour ago',
    type: 'Assignments',
    category: 'assignments',
    read: true,
    unread: false,
    severity: 'success',
  },
  {
    notificationId: 'NOTIF-004',
    title: 'Technician Unavailability',
    message: 'Neha Kapoor status updated to On Leave for Jaipur East.',
    description: 'Neha Kapoor status updated to On Leave for Jaipur East.',
    timestamp: '2 hours ago',
    type: 'System',
    category: 'system',
    read: true,
    unread: false,
    severity: 'warning',
  },
  {
    notificationId: 'NOTIF-005',
    title: 'Job Completed',
    message: 'REQ-010 marked Completed by Aman Singh in Nirman Nagar.',
    description: 'REQ-010 marked Completed by Aman Singh in Nirman Nagar.',
    timestamp: '2.5 hours ago',
    type: 'Assignments',
    category: 'assignments',
    read: true,
    unread: false,
    severity: 'success',
  },
];

export const SEED_AUDIT_EVENTS = [
  {
    action: 'AI_PLAN_GENERATED',
    entityType: 'planner',
    entityId: 'PLAN-2026-10-05-V3',
    entity: 'Schedule v3 optimization draft generated with 8 proposed assignments',
    performedBy: 'AI Dispatch Engine',
    actor: 'AI Dispatch Engine',
    actorType: 'system',
    source: 'AI',
    previousState: 'v2 Confirmed',
    newState: 'v3 Draft',
    reason: 'Automated replan triggered due to overnight schedule review',
    time: '09:42 AM',
    timestamp: '2026-10-05 09:42:15',
    category: 'schedule',
  },
  {
    action: 'REQUEST_ASSIGNED',
    entityType: 'request',
    entityId: 'REQ-004',
    entity: 'REQ-004 assigned to Alex Johnson (13:00 - 15:00)',
    performedBy: 'AI Dispatch Engine',
    actor: 'AI Dispatch Engine',
    actorType: 'system',
    source: 'AI',
    previousState: 'Unassigned',
    newState: 'Alex Johnson',
    reason: 'Reassigned from Rahul Sharma to Alex Johnson for Jaipur North territorial proximity',
    requestId: 'REQ-004',
    time: '09:40 AM',
    timestamp: '2026-10-05 09:40:02',
    category: 'assignment',
  },
  {
    action: 'REQUEST_COMPLETED',
    entityType: 'request',
    entityId: 'REQ-010',
    entity: 'REQ-010 marked COMPLETED by Aman Singh (09:00 - 10:30)',
    performedBy: 'Aman Singh',
    actor: 'Aman Singh',
    actorType: 'technician',
    source: 'Technician',
    previousState: 'IN_PROGRESS',
    newState: 'COMPLETED',
    reason: 'Job completed on site and verified by customer. Protected from replanning.',
    requestId: 'REQ-010',
    time: '10:30 AM',
    timestamp: '2026-10-05 10:30:00',
    category: 'request',
  },
];

export async function seedDatabase() {
  console.log('[FieldFlow Seeder] Starting database seed...');
  await connectDB();

  // Clear existing collections
  await Promise.all([
    Technician.deleteMany({}),
    ServiceRequest.deleteMany({}),
    Assignment.deleteMany({}),
    ScheduleVersion.deleteMany({}),
    Notification.deleteMany({}),
    AuditLog.deleteMany({}),
  ]);

  console.log('[FieldFlow Seeder] Cleared previous database records.');

  // Insert seed data
  await Technician.insertMany(SEED_TECHNICIANS);
  await ServiceRequest.insertMany(SEED_REQUESTS);
  await Assignment.insertMany(SEED_ASSIGNMENTS);
  await ScheduleVersion.insertMany(SEED_VERSIONS);
  await Notification.insertMany(SEED_NOTIFICATIONS);
  await AuditLog.insertMany(SEED_AUDIT_EVENTS);

  // Validate counts
  const reqCount = await ServiceRequest.countDocuments();
  const techCount = await Technician.countDocuments();
  const asgCount = await Assignment.countDocuments();
  const verCount = await ScheduleVersion.countDocuments();
  const notifCount = await Notification.countDocuments();
  const unreadNotifCount = await Notification.countDocuments({ unread: true });

  console.log('----------------------------------------------------');
  console.log(`[FieldFlow Seeder] Database seeded successfully:`);
  console.log(`  - Total Requests:      ${reqCount} (8 assigned, 2 unassigned, 1 completed)`);
  console.log(`  - Technicians:         ${techCount} (4 available, 1 unavailable)`);
  console.log(`  - Active Assignments:  ${asgCount}`);
  console.log(`  - Schedule Versions:   ${verCount} (v1, v2, v3)`);
  console.log(`  - Notifications:       ${notifCount} (${unreadNotifCount} unread)`);
  console.log('----------------------------------------------------');

  return { reqCount, techCount, asgCount, verCount, notifCount, unreadNotifCount };
}

// Execute directly if run as main script
const isMain = process.argv[1] && (process.argv[1].endsWith('seed.js') || process.argv[1].includes('seed'));
if (isMain) {
  seedDatabase()
    .then(() => {
      console.log('[FieldFlow Seeder] Seed script finished. Exiting.');
      process.exit(0);
    })
    .catch((err) => {
      console.error('[FieldFlow Seeder Error]', err);
      process.exit(1);
    });
}
